import type {
  PosterTask as SharedPosterTask,
  ResearchTask as SharedResearchTask
} from '../shared-sdk';

export type {
  AccountType,
  AuthCodeScene,
  AuthSession,
  BillingDashboard,
  BillingDetailItem,
  BillingDetailListQuery,
  BillingDetailPage,
  BusinessPageQuery,
  BillingSummary,
  BillingTopInstance,
  BillingTopProduct,
  ChangePasswordRequest,
  ChatActionRequiredPayload,
  ChatAttachment,
  ChatCitationPayload,
  ChatCompletionRequest,
  ChatCompletionResponse,
  ChatDeltaPayload,
  ChatDonePayload,
  ChatErrorPayload,
  ChatMessage,
  ChatMetaPayload,
  ChatReasoningPayload,
  ChatRetrievalPayload,
  ChatRoutePayload,
  ChatStreamEvent,
  CheckIcpMaterialsRequest,
  Citation,
  CitationDetail,
  CompleteUploadRequest,
  ConversationStatus,
  ConversationSummary,
  CreateIcpApplicationRequest,
  CreatePosterTaskRequest,
  CreateRefundRequest,
  CreateResearchTaskRequest,
  CreateTicketRequest,
  CurrentUser,
  FileRecord,
  ForgotPasswordChallenge,
  ForgotPasswordChallengeRequest,
  IcpApplication,
  IcpApplicationStatus,
  IcpMaterialCheckIssue,
  IcpMaterialCheckResult,
  IcpMaterialItem,
  InvoiceRecord,
  InvoiceRecordPage,
  LoginRequest,
  LoginType,
  MarketingCampaign,
  MarketingCopyRequest,
  MarketingCopyResult,
  MessageRole,
  MessageStatus,
  MessageType,
  OrderDetail,
  OrderListQuery,
  OrderRecord,
  OrderRecordPage,
  OwnedOffsetPageResult,
  PaginatedResult,
  PosterTask,
  RefundListQuery,
  RefundRecord,
  RefundRecordPage,
  RefundStatus,
  RefundTimelineEntry,
  ReplyTicketRequest,
  ResetPasswordRequest,
  ResearchTask,
  RetrievalSource,
  Scene,
  SendCodeRequest,
  SendCodeResponse,
  ServiceWorkspaceData,
  SessionCancelResult,
  SessionCreateRequest,
  SessionListQuery,
  SessionRetryResult,
  TicketDetail,
  TicketListQuery,
  TicketPriority,
  TicketRecord,
  TicketRecordPage,
  TicketReply,
  TicketStatus,
  ToolCallRecord,
  ToolCallStatus,
  UploadBizType,
  UploadPolicy,
  UploadPolicyRequest,
  UserProfileUpdateRequest
} from '../shared-sdk';

export type ResearchTaskStatus = SharedResearchTask['status'];
export type PosterTaskStatus = SharedPosterTask['status'];
