import { Badge } from "./Badge";

const ZH: Record<string, string> = {
  pending: "待处理",
  pending_review: "待审核",
  pending_payment: "待支付",
  paid: "已支付",
  paying: "支付中",
  processing: "处理中",
  reviewing: "审核中",
  approved: "已通过",
  approve: "已通过",
  rejected: "已驳回",
  reject: "已驳回",
  failed: "失败",
  fail: "失败",
  cancelled: "已取消",
  canceled: "已取消",
  cancel: "已取消",
  success: "成功",
  ok: "正常",
  completed: "已完成",
  complete: "已完成",
  finished: "已完成",
  open: "待处理",
  resolved: "已解决",
  closed: "已关闭",
  active: "进行中",
  running: "进行中",
  queued: "排队中",
  archived: "已归档",
  expired: "已过期",
  draft: "草稿",
  published: "进行中",
  submitted: "已提交",
  materials_pending: "待补材料",
  need_user_input: "等待输入",
  ready: "可用",
  high: "高",
  medium: "中",
  low: "低",
  urgent: "紧急",
  technical_support: "技术支持",
  billing: "费用账单",
  order: "订单",
  icp: "ICP 备案",
};

const TONE: Record<string, "success" | "warning" | "danger" | "info" | "neutral" | "brand"> = {
  pending: "warning",
  pending_review: "warning",
  pending_payment: "warning",
  paying: "info",
  paid: "success",
  processing: "info",
  reviewing: "info",
  approved: "success",
  approve: "success",
  rejected: "danger",
  reject: "danger",
  failed: "danger",
  fail: "danger",
  cancelled: "neutral",
  canceled: "neutral",
  cancel: "neutral",
  success: "success",
  ok: "success",
  completed: "success",
  complete: "success",
  finished: "success",
  open: "warning",
  resolved: "success",
  closed: "neutral",
  active: "brand",
  running: "info",
  queued: "info",
  archived: "neutral",
  expired: "neutral",
  draft: "neutral",
  published: "success",
  submitted: "info",
  materials_pending: "warning",
  need_user_input: "warning",
  ready: "success",
  high: "warning",
  medium: "info",
  low: "neutral",
  urgent: "danger",
};

export function StatusBadge({ status, dot = true, label }: { status?: string; dot?: boolean; label?: string }) {
  const key = (status ?? "").toLowerCase();
  const tone = TONE[key] ?? "neutral";
  const text = label ?? ZH[key] ?? status ?? "未知";
  return <Badge tone={tone} dot={dot}>{text}</Badge>;
}
